name: alameda-francis-deployment

services:
    deployment:
        image: amazonlinux:2023
        platform: linux/arm64
        env_file:
            - path: ./deployment/credentials.env
              required: true
        volumes:
            - .:/app
        build:
            context: .
            dockerfile_inline: |
                FROM amazonlinux:2023

                WORKDIR /app

                RUN curl -fsSL https://rpm.nodesource.com/setup_20.x | bash - 
                RUN yum install -y nodejs && \
                    npm install -g npm@11.2.0
                RUN yum install -y python3 python3-pip 
                RUN yum install -y aws-cli
                RUN yum install -y jq

                ENV PATH="/usr/bin:${PATH}"

                CMD [ "bash", "deployment/deployment.sh" ]

        stdin_open: true # Keep stdin open for interactive mode
        tty: true # Allocate a pseudo-TTY
